# Generated by Django 5.1.1 on 2024-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0002_form1'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
