# Generated by Django 5.1.1 on 2024-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0003_form1_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrineTest',
            fields=[
                ('testid', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('patientid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('colour', models.CharField(max_length=50)),
                ('clarity', models.CharField(max_length=50)),
                ('glucose', models.CharField(max_length=50)),
                ('ketone', models.CharField(max_length=50)),
                ('blood', models.CharField(max_length=50)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('other_test', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('normal_value', models.CharField(max_length=100)),
            ],
        ),
    ]
