# Generated by Django 5.1.1 on 2024-09-30 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0004_urinetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='urinetest',
            name='testdate',
            field=models.DateField(default=datetime.date(2024, 9, 30)),
        ),
    ]
