# Generated by Django 5.1.1 on 2024-09-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0005_urinetest_testdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urinetest',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathoapp.patientmaster'),
        ),
    ]
