# Generated by Django 5.1.1 on 2024-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0007_rename_patientid_urinetest_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urinetest',
            name='normal_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='urinetest',
            name='other_test',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='urinetest',
            name='result',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='urinetest',
            name='testid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
