# Generated by Django 5.1.1 on 2024-10-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0009_urinetest_patient_age_urinetest_patient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('patientid', models.CharField(max_length=255)),
                ('patientname', models.CharField(max_length=50)),
                ('testid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('testdate', models.DateField()),
                ('colour', models.CharField(max_length=50)),
                ('clarity', models.CharField(max_length=50)),
                ('glucose', models.CharField(max_length=50)),
                ('ketone', models.CharField(max_length=50)),
                ('blood', models.CharField(max_length=50)),
                ('ph', models.CharField(max_length=50)),
                ('other_test', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('normal_value', models.CharField(max_length=50)),
            ],
        ),
    ]
