# Generated by Django 5.1.1 on 2024-10-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0010_bloodtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugarTest',
            fields=[
                ('testid', models.IntegerField(primary_key=True, serialize=False)),
                ('testdate', models.DateField()),
                ('blood_sugar_fasting', models.CharField(max_length=50)),
                ('blood_sugar_pp', models.CharField(max_length=50)),
                ('blood_sugar_random', models.CharField(max_length=50)),
                ('urine_sugar_fasting', models.CharField(max_length=50)),
                ('urine_sugar_pp', models.CharField(max_length=50)),
                ('urine_sugar_random', models.CharField(max_length=50)),
                ('acetone', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathoapp.patientmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='BloodTest',
        ),
    ]
