# Generated by Django 5.1.1 on 2024-10-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0014_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
