# Generated by Django 5.1.1 on 2024-10-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0016_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodsugartest',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Form1',
        ),
        migrations.RemoveField(
            model_name='urinetest',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BloodSugarTest',
        ),
        migrations.DeleteModel(
            name='PatientMaster',
        ),
        migrations.DeleteModel(
            name='UrineTest',
        ),
    ]
