# Generated by Django 5.1.1 on 2024-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0019_haematology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haematology',
            name='normal_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='haematology',
            name='other_test',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='haematology',
            name='remarks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='haematology',
            name='result',
            field=models.CharField(max_length=100),
        ),
    ]
