# Generated by Django 5.1.1 on 2024-10-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0020_alter_haematology_normal_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haematology',
        ),
    ]
