# Generated by Django 5.0.6 on 2024-11-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0022_haematology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathoinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add1', models.CharField(max_length=50)),
                ('add2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('phone_off', models.CharField(max_length=100)),
                ('phone_resi', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('cgstno', models.CharField(max_length=50)),
                ('cstno', models.CharField(max_length=50)),
                ('panno', models.CharField(max_length=50)),
                ('term1', models.CharField(max_length=50)),
                ('term2', models.CharField(max_length=50)),
            ],
        ),
    ]
