# Generated by Django 5.1.1 on 2024-11-16 13:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0026_kidney'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urine',
            fields=[
                ('test_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('test_date', models.DateField(default=datetime.datetime.now)),
                ('colour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('appearance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sediment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reaction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('albumin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puscells', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rbc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('epithelialcells', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bilesalt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aceyone', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('casts', models.CharField(blank=True, max_length=100, null=True)),
                ('crystals', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('microorganism', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bilepigment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('occultblood', models.CharField(blank=True, max_length=100, null=True)),
                ('other_test', models.CharField(blank=True, max_length=100, null=True)),
                ('other_test_result', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('patientname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathoapp.patientmaster')),
            ],
        ),
    ]
