# Generated by Django 5.1.1 on 2024-11-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0027_urine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('Urine', 'Urine Test'), ('BloodSugar', 'Blood Sugar Test'), ('Haematology', 'Haematology Test'), ('Kidney', 'Kidney Test'), ('BloodSugar', 'Blood Sugar Test'), ('Liver', 'Liver Test'), ('Lipid', 'Lipid Test'), ('Thyroid', 'Thyroid Test')], max_length=50)),
                ('test_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='pathoapp.patientmaster')),
            ],
        ),
    ]
