# Generated by Django 5.1.1 on 2025-02-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0033_alter_haematology_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsugar',
            name='test_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
