# Generated by Django 5.1.1 on 2025-02-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0034_alter_bloodsugar_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidney',
            name='test_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
