# Generated by Django 5.1.1 on 2025-02-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0039_tempalltest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempAllTest',
            new_name='view_all_tests',
        ),
    ]
