# Generated by Django 5.1.1 on 2025-02-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0040_rename_tempalltest_view_all_tests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='view_all_tests',
            new_name='TempAllTest',
        ),
        migrations.AlterField(
            model_name='hiv',
            name='test_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microalbumin',
            name='test_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
