# Generated by Django 5.1.1 on 2025-02-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0041_rename_view_all_tests_tempalltest_alter_hiv_test_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiv',
            name='test_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microalbumin',
            name='test_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
