# Generated by Django 5.1.1 on 2025-02-22 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0044_tempalltest_delete_tempalltests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempalltest',
            old_name='test_remark',
            new_name='test_name',
        ),
    ]
