# Generated by Django 5.1.1 on 2025-02-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0045_rename_test_remark_tempalltest_test_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempAllTest',
        ),
    ]
