# Generated by Django 5.1.1 on 2025-02-22 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathoapp', '0050_bloodsugar_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidney',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathoapp.doctor'),
        ),
    ]
